# Generated by Django 5.0.2 on 2024-03-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('laguage', models.CharField(choices=[('AR', 'Arabic'), ('EN', 'English'), ('FR', 'French')], max_length=2)),
                ('cover', models.URLField()),
                ('trailer', models.URLField()),
                ('release_year', models.IntegerField()),
                ('director', models.CharField(max_length=200)),
                ('box_office', models.FloatField()),
                ('in_theater', models.BooleanField()),
                ('genre', models.ManyToManyField(to='movie.genre')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
