# Generated by Django 5.0.2 on 2024-03-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='synopsis',
            field=models.CharField(default='this is a small description for the movie that was added as a test and it assured that new data will arrive after like 9 million years maybe i dont know', max_length=2500),
            preserve_default=False,
        ),
    ]
